config/routes.rb
Hypertasking::Application.routes.draw do
  resources :users
  resources :sessions, only: [:create, :destroy, :new]

  root to: 'static_pages#home'
  match '/about', to: 'static_pages#about'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :password, :password_confirmation
  has_secure_password

  before_save {|user| user.email = email.downcase}
  before_save :create_remember_token
  
  validates :first_name,
    presence: true, 
    length: {maximum: 50}

  validates :last_name,
    presence: true, 
    length: {maximum: 50}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
    presence: true,
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}

  validates :password,
    presence: true,
    length: {minimum: 6}

  validates :password_confirmation,
    presence: true

  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if signed_in?
      flash[:info] = "You're already signed in!"
      redirect_to current_user
    end
  end

  def create
    user = User.find_by_email params[:session][:email]
    respond_to do |format|
      if user
        if user.authenticate params[:session][:password]
          sign_in user
          flash[:success] = 'Welcome back, ' + user.first_name + '.'
          format.js {
            render js: "window.location.replace('#{redirect_back_or user_path(user)}')"
          }
        else
          format.js {
            render template: 'shared/ujs/form_errors.js.erb',
            locals: {
              ids: ['password'],
              full_messages: ['Wrong password.']
            }
          }
        end
      else
        format.js {
          render template: 'shared/ujs/form_errors.js.erb',
          locals: {
            ids: ['email'],
            full_messages: ['No user with that email exists.']
          }
        }
      end
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      flash.keep
      redirect_to current_user
    end
  end

  def about
  end
end

app/controllers/users_controller.rb
require 'open-uri'

class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:show, :edit, :update, :destroy]
  before_filter :correct_user, only: [:show, :edit, :update, :destroy]

  def show
    flash[:oblique] = JSON.parse(open('http://oblique.heroku.com/api/random').read)['strategy']

    respond_to do |format|
      format.html
      format.json
    end
  end

  def create
    @user = User.new params[:user]

    respond_to do |format|
      if @user.save
        sign_in @user
        flash[:success] = 'Welcome to Hypertasking!'
        format.js {
          render js: "window.location.replace('#{user_path(@user)}')"
        }
      else
        format.js {
          render template: 'shared/ujs/form_errors.js.erb',
          locals: {
            ids: @user.errors,
            full_messages: @user.errors.full_messages 
          }
        }
      end
    end
  end

  def new
    if signed_in?
      flash[:info] = "You're already signed in!"
      redirect_to current_user
    else
      @user = User.new
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update_attributes params[:user]
        sign_in @user
        flash[:success] = 'You successfully updated your profile.'
        format.js {
          render js: "window.location.replace('#{user_path(@user)}')"
        }
      else
        format.js {
          render template: 'shared/ujs/form_errors.js.erb',
          locals: {
            ids: @user.errors,
            full_messages: @user.errors.full_messages
          }
        }
      end
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "You've deleted your account. Sad to see you go."
    redirect_to root_path
  end

  private

  def signed_in_user
    unless signed_in?
      store_location
      flash[:notice] = 'You need to be signed in to do that.'
      redirect_to signin_path
    end
  end

  def correct_user
    begin
      @user = User.find params[:id]
    rescue ActiveRecord::RecordNotFound
      @user = 0
    ensure
      unless current_user? @user
        flash[:error] = 'Authorized personnel only.'
        redirect_to root_path
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token cookies[:remember_token]
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    self.current_user = nil
    cookies.delete :remember_token
  end

  def redirect_back_or default
    redir = session[:return_to] || default
    session.delete :return_to
    redir
  end

  def store_location
    session[:return_to] = request.fullpath
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.haml
%footer.footer
  - year = Time.new.strftime '%Y'
  - if year.to_i > 2012
    = succeed '-' + year do
      &copy; 2012
  - else
    &copy; 2012
  = link_to 'Dan Mundy', 'http://www.processthings.com/'
  %nav
    %ul
      %li= link_to 'About', about_path
      %li= link_to 'Twitter', 'http://twitter.com/hypertaskingapp'

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %h1= link_to 'Hypertasking', root_path, class: 'logo', alt: 'Home'
      %ul.nav.pull-right
        - if signed_in?
          %li.dropdown
            %a.dropdown-toggle{href: '#', 'data-toggle' => 'dropdown'}
              %i.icon-white.icon-user
              = current_user.first_name + ' ' + current_user.last_name
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to current_user do
                  %i.icon-list
                  Your tasks
              %li
                = link_to edit_user_path(current_user) do
                  %i.icon-cog
                  Settings
              %li.divider
              %li
                = link_to signout_path, method: 'delete' do
                  %i.icon-eject
                  Sign out
        - else
          %li= link_to 'Sign in', signin_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      Hypertasking 
      \|
      = yield :title
    = favicon_link_tag asset_path 'favicon.ico'
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Yesteryear', media: 'all'
    = stylesheet_link_tag 'application', controller.controller_name, media: 'all'
    = javascript_include_tag 'application', 'app-wide', controller.controller_name
    %meta{name: 'viewport', content: 'user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0'}/
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container
      .row.alerts
        - flash.each do |key, value|
          .span4
            %aside.alert.fade.in{class: "alert-#{key}"}
              %button.close{'data-dismiss' => 'alert'} &times;
              - if key == :oblique
                %strong
                  = succeed ':' do
                    = link_to 'Oblique Strategy', 'http://oblique.heroku.com/'
              = value
      = yield
      = render 'layouts/footer'

app/views/shared/ujs/form_errors.js.erb
var errors = {ids: [], full_messages: []};

<% ids.each do |id| %>
  errors.ids.push("#<%= id %>");
<% end %>

<% full_messages.each do |message| %>
  errors.full_messages.push("<%= message %>");
<% end %>

$.each(errors.ids, function(i, value) {
  // Only display one error per form element. Rails usually returns the most pertinent one first.
  if (errors.ids[i] == errors.ids[i-1]) {
    return true;
  }

  // Animate with a fade if changing the error message
  if ($('.control-group' + errors.ids[i]).hasClass('error')) {
    if ($('.control-group' + errors.ids[i] + ' .help-inline').html() != errors.full_messages[i]) {
      $('.control-group' + errors.ids[i] + ' .help-inline')
      .fadeOut(function() {
        $(this).html(errors.full_messages[i])
        .fadeIn();
      });
    }
  } else { // Slide down a new error message
    $('.control-group' + errors.ids[i])
    .addClass('error')
    .find('.help-inline')
    .html(errors.full_messages[i])
    .slideDown();
  }
});

// Slide up fixed errors
$('.control-group:not(' + errors.ids.join() + ')')
.removeClass('error')
.find('.help-inline')
.slideUp();

app/views/static_pages/about.html.haml
- provide :title, 'About'
.hero-unit
  %h1
    More about
    %span.logo Hypertasking
  %p Hypertasking aims to be the best to-do list app out there. Not the simplest, not the quickest, and not the most fully-featured hunk of junk. Just the best. So if you want a to-do list app that provides a truly productive experience, stick around for further updates.
  %h2 What is hypertasking all about?
  %p Good question. Hypertasking, the concept, is a state of mind and body that's super-productive. It's about finding and exploiting that hidden zone between rushing and slogging, that perfect balance between too much and not enough. Hypertasking is a marvellous, pumping flow that almost seems to carry you along through a list of concrete and manageable tasks. When you're hypertasking, you're unstoppable.
  %p When I set out to make this app, I wanted to make something that would easily allow people to get into this high-throughput mode without worrying too much about the limitations or capabilities of the the task management system they're using. I wanted to help people recreate the conditions that allow them to complete lots and lots of tasks in rapid succession, not just become a place to dump a large, disorderly list of things to do. In order to do this, I've set out some goals for this project.
  %h2
    The vision of 
    %span.logo Hypertasking
  %ul
    %li
      %p
        Style, ease, quality, 
        = link_to 'velocity, design, comfort', 'http://en.wikipedia.org/wiki/Velocity_:_Design_:_Comfort'
    %li
      %p A well-organized interface for planning, gearing up, and zipping through tasks
    %li
      %p Customizable without being fiddly and wasting all your time
    %li
      %p Automatic reminders based on location and time so you can clear your head and focus
    %li
      %p Prioritization, so you know what's important
    %li
      %p Unique special sauce
  %h2 What next?
  %p
    = link_to 'Sign up', signup_path
    and start using it. It's constantly being improved, and you'll see the changes as they come. Follow
    = precede '@' do
      = link_to 'hypertaskingapp', 'http://twitter.com/hypertaskingapp'
    on Twitter to stay updated, or
    = link_to 'fork it on Github', 'https://github.com/exchgr/Hypertasking'
    if you think I'm not moving fast enough.

app/views/static_pages/home.html.haml
- provide :title, 'Home'
.hero-unit
  %h1 
    This is 
    = succeed '.' do
      %span.logo Hypertasking
  %p
    Are you fed up with the state of to-do list apps? Do you feel like you're not getting enough done? Fear not. Hypertasking is coming.
  %p.right
    = link_to 'Sign up now', signup_path, alt: 'Sign up', class: 'btn btn-primary btn-large'
    = link_to 'Wait, what?', about_path, alt: 'About', class: 'btn btn-large'

app/views/users/edit.html.haml
- provide :title, 'Edit your profile'
.modal.fade.hide#delete-account-confirm
  .modal-header
    %button.close{'data-dismiss' => 'modal'} &times;
    %h3 For reals?
  .modal-body
    %p Are you sure you wanna delete your account? You can't go back on it. A deal's a deal.
  .modal-footer
    %a.btn{href: '#', 'data-dismiss' => 'modal'}
      Not really
    = link_to @user, method: :delete, class: 'btn btn-danger' do
      %i.icon-trash.icon-white
      Delete
.row
  .span4.offset4
    .page-header
      %h1 Settings
    = form_for @user, remote: true, html: {novalidate: 'novalidate'} do |f|
      %h2 Edit your profile
      .control-group#first_name
        = f.text_field :first_name, placeholder: 'First name'
        %br/
        .help-inline
      .control-group#last_name
        = f.text_field :last_name, placeholder: 'Last name'
        %br/
        .help-inline
      .control-group#email
        = f.email_field :email, placeholder: 'Email'
        %br/
        .help-inline
      .control-group#password
        = f.password_field :password, placeholder: 'Password'
        %br/
        .help-inline
      .control-group#password_confirmation
        = f.password_field :password_confirmation, placeholder: 'Type it again.'
        %br/
        .help-inline
      %p
        %a.btn.btn-danger#delete-account{href: '#'}
          %i.icon-trash.icon-white
        %span.pull-right
          = link_to 'Cancel', 'javascript:history.back();'
          or
          = f.submit 'Save', class: 'btn btn-primary'
    %h2 Manage your data
    %p= link_to 'Download it as a JSON file', action: 'show', format: :json

app/views/users/new.html.haml
- provide :title, 'Sign up'
.row
  .span4.offset4
    .page-header
      %h1 Sign up
    = form_for @user, remote: true, html: {novalidate: 'novalidate'} do |f|
      .control-group#first_name
        = f.text_field :first_name, placeholder: 'First name'
        %br/
        .help-inline
      .control-group#last_name
        = f.text_field :last_name, placeholder: 'Last name'
        %br/
        .help-inline
      .control-group#email
        = f.email_field :email, placeholder: 'Email'
        %br/
        .help-inline
      .control-group#password
        = f.password_field :password, placeholder: 'Password'
        %br/
        .help-inline
      .control-group#password_confirmation
        = f.password_field :password_confirmation, placeholder: 'Type it again.'
        %br/
        .help-inline
      %p
        = link_to 'Sign in instead', signin_path, class: 'btn'
        %span.pull-right= f.submit 'Sign up', class: 'btn btn-primary'

app/views/users/show.html.haml
- provide :title, @user.first_name + ' ' + @user.last_name + '\'s tasks'
.page-header
  %h1= @user.first_name + ' ' + @user.last_name + '’s tasks'
// Add 'Your' logic

.row
  .span3
    %ul.nav.nav-list
      %li.active
        = link_to '#everything', 'data-toggle' => 'tab' do
          %i.icon-white.icon-asterisk
          Everything
      %li
        = link_to '#right-now', 'data-toggle' => 'tab' do
          %i.icon-play
          Right now
      %li
        = link_to '#upcoming', 'data-toggle' => 'tab' do
          %i.icon-calendar
          Upcoming
      %li.divider
      %li
        = link_to '#important', 'data-toggle' => 'tab' do
          %i.icon-exclamation-sign
          Important
      %li
        = link_to '#long', 'data-toggle' => 'tab' do
          %i.icon-time
          Long tasks
      %li
        = link_to '#quick', 'data-toggle' => 'tab' do
          %i.icon-fast-forward
          Quick tasks
  .span9
    .tab-content
      .tab-pane.active#everything
        %h2
          %i.icon-asterisk
          Everything
        %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam laoreet enim vitae leo scelerisque porta at at nibh. Duis eleifend nisi sed est vulputate dictum. Fusce interdum dui non libero venenatis in condimentum nisi fringilla. Etiam et egestas nunc. Sed sodales est eget nunc ultrices congue interdum justo consectetur. Fusce massa nibh, feugiat sit amet convallis nec, euismod in nisl. Nulla facilisi. Integer feugiat, mauris sed dapibus convallis, massa justo congue velit, non pellentesque lorem mi ac nulla. Ut nisl lorem, malesuada et varius nec, vestibulum ac felis. Aenean feugiat rhoncus purus ut tincidunt.
      .tab-pane#right-now
        %h2
          %i.icon-play
          Right now
        %p Donec ornare nulla libero. Phasellus semper dictum enim. Nullam ultrices urna dignissim justo consectetur hendrerit. Ut mollis lacus nec risus cursus pretium. Phasellus dolor orci, pharetra ut mollis id, varius ut nisl. Suspendisse dapibus augue vel diam bibendum ut auctor turpis tempus. Duis elementum nibh lorem. Sed ullamcorper diam sit amet nisi posuere at volutpat eros mattis. Nulla at lacus elit, nec tincidunt elit. Nunc odio neque, interdum nec placerat non, pharetra eget nibh. Pellentesque semper faucibus vestibulum. Nullam vel sem elementum risus feugiat suscipit vitae non risus. Mauris porta pellentesque est at lacinia.
      .tab-pane#upcoming
        %h2
          %i.icon-calendar
          Upcoming
        %p Nulla pharetra lacus eget dolor vehicula aliquam ut eu est. Duis vitae viverra sem. Vestibulum convallis pretium volutpat. Etiam aliquam, magna et placerat euismod, tellus neque porta lorem, eget blandit turpis orci at turpis. Nam sollicitudin, justo id semper facilisis, mauris ligula adipiscing nulla, in mollis augue mi ut nisl. In hac habitasse platea dictumst. Aliquam viverra, nunc eu gravida faucibus, velit odio condimentum massa, non ornare massa odio nec leo. Ut enim sem, fermentum ut lacinia eget, auctor sit amet nulla. Proin interdum dui ac leo consequat fringilla. Donec gravida ornare urna, nec blandit purus consectetur eu. Quisque suscipit est sit amet mauris placerat eget posuere erat venenatis. Pellentesque tincidunt dapibus massa ac tincidunt.
      .tab-pane#important
        %h2
          %i.icon-exclamation-sign
          Important
        %p Praesent augue magna, mattis vel rutrum egestas, dignissim vel tortor. Sed adipiscing risus in ipsum rhoncus non fermentum nulla sollicitudin. In blandit mauris eget purus congue ut elementum metus vehicula. Curabitur vehicula neque id risus porta dapibus. Duis vehicula laoreet enim. Curabitur et nunc in erat posuere tempor ac sed felis. Suspendisse sodales risus eget metus blandit nec rhoncus felis bibendum. Phasellus velit tellus, egestas sit amet tincidunt a, fringilla eu est. Suspendisse sem nibh, mattis et ultricies eget, sodales sit amet enim. Pellentesque hendrerit egestas eleifend. Nullam vel felis nisi. Ut et rhoncus eros. Proin tempus luctus risus.
      .tab-pane#long
        %h2
          %i.icon-time
          Long tasks
        %p Mauris commodo erat ut arcu cursus blandit. Nullam non nibh vel nulla sollicitudin consectetur in non enim. Nullam justo ipsum, porttitor eget bibendum sed, scelerisque id nibh. Nunc accumsan, quam sit amet tristique egestas, erat velit pellentesque diam, ac condimentum elit diam quis massa. Mauris rutrum risus non nisi semper sit amet porta neque congue. Vivamus gravida felis nec nulla suscipit egestas. Etiam dictum massa sed purus molestie blandit. Aenean at nisi eu eros fermentum placerat at vitae nisi. Nullam sagittis aliquet nisi, eget posuere nibh rutrum condimentum. Nullam eget ante vel ligula porta faucibus. Donec id urna leo, eu iaculis augue.
      .tab-pane#quick
        %h2
          %i.icon-fast-forward
          Quick tasks
        %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam laoreet enim vitae leo scelerisque porta at at nibh. Duis eleifend nisi sed est vulputate dictum. Fusce interdum dui non libero venenatis in condimentum nisi fringilla. Etiam et egestas nunc. Sed sodales est eget nunc ultrices congue interdum justo consectetur. Fusce massa nibh, feugiat sit amet convallis nec, euismod in nisl. Nulla facilisi. Integer feugiat, mauris sed dapibus convallis, massa justo congue velit, non pellentesque lorem mi ac nulla. Ut nisl lorem, malesuada et varius nec, vestibulum ac felis. Aenean feugiat rhoncus purus ut tincidunt.

app/views/users/show.json.erb
<%= raw @user.to_json %>
<% # This will need more as actual features get built. %>